[input]
html_selector = "main"
base_directory = "/homestore1/smbshare/Andi/blog-ydnaz/output"

[[input.files]]
path = "Perbuahan lisensi di hashicorp membuat OpenTofu lahir sebagai fork..html"
url = "/Perbuahan lisensi di hashicorp membuat OpenTofu lahir sebagai fork..html"
title = "OpenTofu"

[[input.files]]
path = "Podman, Linux, Container.html"
url = "/Podman, Linux, Container.html"
title = "Podman Container"

[[input.files]]
path = "Volume Storage management di Windows.html"
url = "/Volume Storage management di Windows.html"
title = "Microsoft Storage Space"

[[input.files]]
path = "install-dan-setup-mariadb-cluster-menggunakan-galera-cluster.html"
url = "/install-dan-setup-mariadb-cluster-menggunakan-galera-cluster.html"
title = "Install dan Setup Mariadb Cluster menggunakan Galera Cluster"

[[input.files]]
path = "use-lvm-cache-for-storage-tiering-to-speed-up-spinning-disk-with-small-ssd.html"
url = "/use-lvm-cache-for-storage-tiering-to-speed-up-spinning-disk-with-small-ssd.html"
title = "Use LVM-cache for Storage Tiering to speed up spinning disk with small SSD."

[[input.files]]
path = "Bhyve the BSD Hypervisor.html"
url = "/Bhyve the BSD Hypervisor.html"
title = "Berkenalan dengan Bhyve The BSD Hypervisor"

[[input.files]]
path = "install-openvpn-di-debian-linux-server.html"
url = "/install-openvpn-di-debian-linux-server.html"
title = "Install dan setting Openvpn di Debian Jessie"

[[input.files]]
path = "apa-itu-cluster.html"
url = "/apa-itu-cluster.html"
title = "Apa itu Cluster?"
